### ISSUE TITLE
What is the definition of `1-shot` and `2-shot` in paper?

### ISSUE THREAD

**Issue by Leolty** [wenhuchen/TableCoT#1]
Hi, Prof. Chen,

I am a bit confused about the definition of `1-shot` and `2-shot` mentioned in your EACL paper. Does `1-shot` refer to a single table with 4 QA pairs (as shown in the Github prompt)? And does `2-shot` mean there are 2 tables used as demonstrations? Or does the Github repository actually is doing a `4-shot`?

Thanks :)

**Comment by wenhuchen** [comment]
Hi there,

Thanks for raising this. I should have been more explicit. The paper contains the initial experiment results, where 1-shot means 1 table + 2-4 example (depending on the task).

**Comment by Leolty** [comment]
Thank you very much! I was wondering if you could kindly share the second table for `2-shot` if you still have the prompt record.

**Comment by wenhuchen** [comment]
You can just take the first two demonstrations. The performance shouldn't change too much.

**Comment by Leolty** [comment]
Thanks :)
